<?php

namespace EscaleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * categRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categRepository extends EntityRepository
{
}
