admin_service_index:
    path:     /
    defaults: { _controller: "EscaleBundle:Service:index" }
    methods:  GET

admin_service_show:
    path:     /{id}/show
    defaults: { _controller: "EscaleBundle:Service:show" }
    methods:  GET

admin_service_new:
    path:     /new
    defaults: { _controller: "EscaleBundle:Service:new" }
    methods:  [GET, POST]

admin_service_edit:
    path:     /{id}/edit
    defaults: { _controller: "EscaleBundle:Service:edit" }
    methods:  [GET, POST]

admin_service_delete:
    path:     /{id}/delete
    defaults: { _controller: "EscaleBundle:Service:delete" }
    methods:  DELETE
