admin_sport_index:
    path:     /
    defaults: { _controller: "EscaleBundle:Sport:index" }
    methods:  GET

admin_sport_show:
    path:     /{id}/show
    defaults: { _controller: "EscaleBundle:Sport:show" }
    methods:  GET

admin_sport_new:
    path:     /new
    defaults: { _controller: "EscaleBundle:Sport:new" }
    methods:  [GET, POST]

admin_sport_edit:
    path:     /{id}/edit
    defaults: { _controller: "EscaleBundle:Sport:edit" }
    methods:  [GET, POST]

admin_sport_delete:
    path:     /{id}/delete
    defaults: { _controller: "EscaleBundle:Sport:delete" }
    methods:  DELETE
